### ISSUE TITLE
Question: what sever?

### ISSUE THREAD

**Issue by djzort** [robrwo/CatalystX-Statsd#2]
Im very grateful that you authored this module. I had actually been asking (bugging) JJNAPIORK to do something along these lines. So my sincere thanks for your work and for publishing it. Also your working maintaining the statsd client.

I am curious what you're using to receive these catalyst statsd's and how you're using them?

Are you using them for profiling? perhaps generating some nice flame graphs?

**Comment by robrwo** [comment]
@djzort Thank you for the feedback. We use collectd, although we're not currently using the Catalyst::Statsd module. The purpose is for superficial profiling.
